CREATE TABLE IF NOT EXISTS `wp_TimeBank` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`acount`  varchar(10) NOT NULL  COMMENT '账户',
`tradeDate` date NOT NULL COMMENT '交易日期',
`incommeExpense`  int(2) NOT NULL  COMMENT '收支标志(0:收入，1:支出)',
`amount` int(10) NOT NULL  COMMENT '金额(时间)',
`balance` int(10) NOT NULL  COMMENT '余额',
`memo`  varchar(100) NOT NULL  COMMENT '备注',
`handlerName` varchar(10) NOT NULL  COMMENT '经办人',
`ceateTime` timestamp NOT NULL  COMMENT '更新时间',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('TimeBank','时间银行','0','','1','["acount","tradeDate","incommeExpense","amount","balance","memo","handlerName","ceateTime"]','1:基础','','','','','id:编号\r\acount:账户\r\ntradeDate:交易日期\r\nincommeExpense:收支标志(0:收入，1:支出)\r\namountz:金额(时间)\r\nbalance:余额\r\nmemo:备注\r\nhandlerName:经办人\r\nceateTime:更新时间\r\nids:操作:[EDIT]|编辑,[DELETE]|删除,lists?target_id=[id]&target=_blank&_controller=Sn|成员管理,preview?id=[id]&target=_blank|预览','20','title','','1396061373','1447756274','1','MyISAM','TimeBank');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('acount','账户','varchar(10) NOT NULL','string','','','1','','0','TimeBank','0','1','1422000992','1422000992','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('tradeDate','交易日期','date NOT NULL','date','','','1','','0','TimeBank','0','1','1422000992','1422000992','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('incommeExpense','收支标志(0:收入，1:支出)','int(2) NOT NULL','num','','','1','','0','TimeBank','0','1','1422000992','1422000992','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('amount','金额(时间)','int(10) NOT NULL','num','','','1','','0','TimeBank','0','1','1422000992','1422000992','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('balance','余额','int(10) NOT NULL','num','','','1','','0','TimeBank','0','1','1422000992','1422000992','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('memo','备注','varchar(100) NOT NULL','string','','','1','','0','TimeBank','0','1','1422000992','1422000992','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('handlerName','经办人','varchar(10) NOT NULL','string','','','1','','0','TimeBank','0','1','1422000992','1422000992','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ceateTime','更新时间','timestamp NOT NULL','datetime','','','4','','0','TimeBank','0','1','1422000992','1422000992','','3','','regex','','3','function');
UPDATE `wp_attribute` a, wp_model m SET a.model_id = m.id WHERE a.model_name=m.`name`;
