CREATE TABLE IF NOT EXISTS `wp_time_bank` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`acount`  varchar(10) NULL  COMMENT '账户',
`tradeDate`  int(10) NULL  COMMENT '交易日期',
`incommeExpense`  int(2) NULL  COMMENT '收支标志(0:收入，1:支出)',
`project`  int(2) NULL  COMMENT '项目(0:看电视，1:玩手机,2:做作业,3:看书)',
`amount`  int(10) NULL  COMMENT '金额(时间)',
`memo`  varchar(255) NULL  COMMENT '备注',
`handlerName`  varchar(10) NULL  COMMENT '经办人',
`ceateTime`  int(10) NULL  COMMENT '更新时间',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('time_bank','时间银行','0','','1','["acount","tradeDate","incommeExpense","project","memo","handlerName","ceateTime","amount"]','1:基础','','','','','acount:账户\r\ntradeDate|time_format:交易日期\r\nincommeExpense|get_name_by_status:收支标志\r\nproject|get_name_by_status:项目\r\namount:金额(时间)\r\nmemo:备注\r\nhandlerName:经办人\r\nceateTime|time_format:更新时间\r\nids:操作:[EDIT]&id=[id]|编辑,[DELETE]&id=[id]|删除','10','from_unixtime(tradeDate,\'%Y%m%d\'):请输入交易日期搜索','','1498101437','1498120519','1','MyISAM','TimeBank');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('acount','账户','varchar(10) NULL','string','','','1','','0','time_bank','0','1','1498101538','1498101538','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('tradeDate','交易日期','int(10) NULL','date','','','1','','0','time_bank','0','1','1498101582','1498101582','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('incommeExpense','收支标志(0:收入，1:支出)','int(2) NULL','radio','','','1','0:收入\r\n1:支出','0','time_bank','0','1','1498105445','1498101608','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('project','项目(0:看电视，1:玩手机,2:做作业,3:看书)','int(2) NULL','radio','','','1','0:看电视\r\n1:玩手机\r\n2:做作业\r\n3:看书\r\n4:其他','0','time_bank','0','1','1498105422','1498101745','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('amount','金额(时间)','int(10) NULL','num','','','1','','0','time_bank','0','1','1498120468','1498101766','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('memo','备注','varchar(255) NULL','string','','','1','','0','time_bank','0','1','1498101798','1498101798','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('handlerName','经办人','varchar(10) NULL','string','','','1','','0','time_bank','0','1','1498101906','1498101824','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ceateTime','更新时间','int(10) NULL','date','','','1','','0','time_bank','0','1','1498101852','1498101852','','3','','regex','','3','function');
UPDATE `wp_attribute` a, wp_model m SET a.model_id = m.id WHERE a.model_name=m.`name`;
CREATE TABLE IF NOT EXISTS `wp_time_deposit` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`targetName`  varchar(255) NULL  COMMENT '目标名',
`target`  int(10) NULL  COMMENT '目标',
`time`  int(10) NULL  COMMENT '时间',
`handlerName`  varchar(10) NULL  COMMENT '经办人',
`ceateTime`  int(10) NULL  COMMENT '更新时间',
`status`  int(2) NULL  DEFAULT 0 COMMENT '状态',
`expiate`  int(10) NULL  COMMENT '有效期',
`memo`  varchar(255) NULL  COMMENT '备注',
`acount`  varchar(10) NULL  COMMENT '帐号',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('time_deposit','时间储蓄','0','','1','["acount","targetName","target","expiate","time","status","memo","ceateTime","handlerName"]','1:基础','','','','','acount:帐号\r\ntargetName:目标名\r\ntarget:目标\r\nexpiate|time_format:有效期\r\ntime:时间\r\nstatus|get_name_by_status:状态\r\nmemo:备注\r\nhandlerName:经办人\r\nceateTime|time_format:更新时间\r\nids:操作:[EDIT]&id=[id]|编辑,[DELETE]&id=[id]|删除','10','project:请输入项目名搜索','','1498442261','1498456728','1','MyISAM','TimeBank');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('targetName','目标名','varchar(255) NULL','string','','','1','','0','','1','1','1498449424','1498442625','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('target','目标','int(10) NULL','num','','','1','','0','','1','1','1498442988','1498442988','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('time','时间','int(10) NULL','num','','','1','','0','','0','1','1498446118','1498446118','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('handlerName','经办人','varchar(10) NULL','string','','','1','','0','','0','1','1498446181','1498446181','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ceateTime','更新时间','int(10) NULL','datetime','','','1','','0','','0','1','1498446253','1498446253','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('status','状态','int(2) NULL','radio','0','','1','0:努力中\r\n1:达成\r\n2:失败\r\n3:放弃','0','','0','1','1498447673','1498446482','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('expiate','有效期','int(10) NULL','datetime','','','1','','0','','0','1','1498446641','1498446641','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('memo','备注','varchar(255) NULL','string','','','1','','0','','0','1','1498446884','1498446884','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('acount','帐号','varchar(10) NULL','string','','','1','','0','','0','1','1498456509','1498456022','','3','','regex','','3','function');
UPDATE `wp_attribute` a, wp_model m SET a.model_id = m.id WHERE a.model_name=m.`name`;